# -*- coding: utf-8 -*-
"""Basic_Programs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOTdXwm2yZCAEoTu8QVuGoIZNj9QVPjB
"""

# palindrome number

a=151
temp=a
rev=0

while a>0:
  r=a%10
  rev=(rev*10)+r
  a=a//10

if temp==rev:
  print('The palindrome number')

else:
  print('Not Palindrome number')

# swapping
a=250
b=100
temp=a
a=b
b=temp

print('The after Swapping number a is:',a)
print('The befor Swapping Number b is:',b)

# Factorial Number

a=5
factorial=1
for i in range(1,a+1):
     factorial*=i
print('the favtorial a is:',factorial)

# Even Numbers

for i in range(1,11):
   if i%2==0:
     print('Even numbers:',i)

# odd Numbers

for i in range(1,11):
  if i%2!=0:
    print('odd numbers:',i)

# Even numbers and Odd Numbers

for i in range(1,21):
  if i%2==0:
    print('even numberes:',i)
  else:
    print('odd numberes:',i)

